workflows:
  ios-release:
    name: iOS Release
    max_build_duration: 60
    instance_type: mac_mini_m1
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_STORE_CONNECT_KEY_IDENTIFIER: "A899CQL63F"
        APP_STORE_CONNECT_ISSUER_ID: "e1f98c09-18c3-4d1a-91e2-cace11d10093"
        APP_STORE_CONNECT_PRIVATE_KEY: |
          -----BEGIN PRIVATE KEY-----
          MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgc/D9bGNuNJ5cZRbw
          B6lR+r8/FoPUaBEfRuvogE8fXK2gCgYIKoZIzj0DAQehRANCAARSf/ywUg8HL1YI
          1tTrA4rwU6utA7g2dbyqilw0K/9nMY1AL9lVM6L2mU3gwLi9xzMtFUZDB3W675VP
          1PVKIxHg
          -----END PRIVATE KEY-----
    scripts:
      - name: Set up code signing
        script: |
          keychain initialize
          app-store-connect fetch-signing-files "com.petshopx2025.app" --type IOS_APP_STORE --create
          keychain add-certificates
          xcode-project use-profiles --export-options-plist=$HOME/export_options.plist
      - name: Get Flutter packages
        script: |
          flutter pub get
      - name: Install CocoaPods
        script: |
          cd ios && pod install
      - name: Build IPA
        script: |
          flutter build ipa --release --export-options-plist=$HOME/export_options.plist
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      email:
        recipients:
          - saidtadjievfaris@icloud.com
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
