import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LanguageProvider extends ChangeNotifier {
  String _currentLanguage = 'ru';
  bool _isInitialized = false;

  String get currentLanguage => _currentLanguage;
  bool get isInitialized => _isInitialized;

  // Языки
  static const Map<String, Map<String, String>> _translations = {
    'ru': {
      'app_name': 'PetPet',
      'home': 'Главная',
      'catalog': 'Каталог',
      'favorites': 'Избранное',
      'profile': 'Профиль',
      'search': 'Поиск',
      'search_hint': 'Поиск питомцев...',
      'categories': 'Категории',
      'all': 'Все',
      'dogs': 'Собаки',
      'cats': 'Кошки',
      'birds': 'Птицы',
      'fish': 'Рыбки',
      'rodents': 'Грызуны',
      'reptiles': 'Рептилии',
      'horses': 'Лошади',
      'other': 'Другие',
      'popular': 'Популярное',
      'new_ads': 'Новые объявления',
      'see_all': 'Все',
      'price': 'Цена',
      'contact_seller': 'Связаться',
      'call': 'Позвонить',
      'telegram': 'Telegram',
      'add_to_favorites': 'В избранное',
      'remove_from_favorites': 'Убрать из избранного',
      'login': 'Войти',
      'register': 'Регистрация',
      'phone': 'Телефон',
      'password': 'Пароль',
      'name': 'Имя',
      'my_ads': 'Мои объявления',
      'settings': 'Настройки',
      'logout': 'Выйти',
      'add_ad': 'Добавить объявление',
      'title': 'Название',
      'description': 'Описание',
      'category': 'Категория',
      'city': 'Город',
      'publish': 'Опубликовать',
      'no_favorites': 'Нет избранных',
      'no_ads': 'Нет объявлений',
      'select_language': 'Выберите язык',
      'language': 'Язык',
      'edit': 'Изменить',
      'edit_profile': 'Редактировать профиль',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'logout_confirm': 'Вы уверены что хотите выйти из аккаунта?',
      'login_prompt': 'Войдите чтобы размещать объявления',
      'login_telegram': 'Войти через Telegram',
      'notifications': 'Уведомления',
      'messages': 'Сообщения',
      'messages_desc': 'Уведомления о новых сообщениях',
      'ads_notifications': 'Объявления',
      'ads_notifications_desc': 'Новые объявления в избранных категориях',
      'news': 'Новости',
      'news_desc': 'Акции и специальные предложения',
      'about': 'О приложении',
      'help': 'Помощь',
      'version': 'Версия',
      'about_text': 'PetPet - удобная площадка для покупки и продажи животных в Узбекистане.',
      'contacts': 'Контакты',
      'close': 'Закрыть',
      'breed': 'Порода',
      'age': 'Возраст',
      'vaccinated': 'Привит',
      'negotiable': 'Торг',
      'popular_queries': 'Популярные запросы',
      'nothing_found': 'Ничего не найдено',
      'try_different': 'Попробуйте изменить запрос',
      'found': 'Найдено',
      'select_category': 'Выберите категорию',
      'select_photo': 'Выберите фото',
      'ad_created': 'Объявление создано',
      'fill_required': 'Заполните обязательные поля',
      'all_products': 'Все товары',
      'search_products': 'Поиск товаров...',
      'animals': 'Животные',
      'choose_pet': 'Выберите питомца',
      'products': 'Товары',
      'for_pets': 'Для ваших питомцев',
      'more': 'Ещё',
      'food': 'Корма',
      'toys': 'Игрушки',
      'cages': 'Клетки',
      'empty_yet': 'Пока пусто',
      'add_favorites_hint': 'Добавляйте понравившиеся\nобъявления в избранное',
      'go_to_search': 'Перейти к поиску',
      'clear': 'Очистить',
      'clear_favorites': 'Очистить избранное?',
      'clear_favorites_hint': 'Все объявления будут удалены из избранного',
      'items_one': 'объявление',
      'items_few': 'объявления',
      'items_many': 'объявлений',
      'new_ad': 'Новое объявление',
      'photos': 'Фотографии',
      'photos_hint': 'Добавьте до 8 фото. Первое фото будет главным',
      'add_photo': 'Добавить фото',
      'main_photo': 'Главное',
      'choose_from_gallery': 'Выбрать из галереи',
      'can_select_multiple': 'Можно выбрать несколько',
      'take_photo': 'Сделать фото',
      'open_camera': 'Открыть камеру',
      'category_and_city': 'Категория и город',
      'main_info': 'Основная информация',
      'ad_title': 'Название объявления',
      'ad_title_hint': 'Например: Британский котёнок, мальчик',
      'enter_title': 'Введите название',
      'enter_price': 'Введите цену',
      'price_negotiable': 'Цена договорная',
      'price_negotiable_hint': 'Цена обсуждается с покупателем',
      'pet_characteristics': 'Характеристики питомца',
      'color': 'Окрас',
      'gender': 'Пол',
      'male': 'Мальчик',
      'female': 'Девочка',
      'vaccinated_hint': 'Питомец имеет все необходимые прививки',
      'ad_description': 'Описание объявления',
      'ad_description_hint': 'Опишите питомца подробнее: характер, особенности...',
      'enter_description': 'Введите описание',
      'contact_info': 'Контактные данные',
      'phone_number': 'Номер телефона',
      'enter_phone': 'Введите телефон',
      'telegram_optional': 'Telegram (необязательно)',
      'free_posting': 'Размещение БЕСПЛАТНО',
      'ad_active_30_days': 'Объявление будет активно 30 дней',
      'promotion': 'Продвижение',
      'your_ad_in_top': 'Ваше объявление будет в топе',
      'days': 'дней',
      'publish_free': 'Опубликовать бесплатно',
      'ad_published': 'Объявление опубликовано!',
      'ad_published_hint': 'Ваше объявление успешно добавлено и уже доступно для просмотра',
      'top_activated': 'TOP активирован!',
      'great': 'Отлично!',
      'max_8_photos': 'Максимум 8 фотографий',
      'add_at_least_one_photo': 'Добавьте хотя бы одно фото',
      'dark_theme': 'Тёмная тема',
      'light_theme': 'Светлая тема',
      'theme': 'Оформление',
      'filter': 'Фильтр',
      'sort_by': 'Сортировка',
      'price_low_high': 'Цена: от низкой к высокой',
      'price_high_low': 'Цена: от высокой к низкой',
      'newest': 'Сначала новые',
      'apply': 'Применить',
      'reset': 'Сбросить',
      'view_grid': 'Сетка',
      'view_list': 'Список',
    },
    'en': {
      'app_name': 'PetPet',
      'home': 'Home',
      'catalog': 'Catalog',
      'favorites': 'Favorites',
      'profile': 'Profile',
      'search': 'Search',
      'search_hint': 'Search pets...',
      'categories': 'Categories',
      'all': 'All',
      'dogs': 'Dogs',
      'cats': 'Cats',
      'birds': 'Birds',
      'fish': 'Fish',
      'rodents': 'Rodents',
      'reptiles': 'Reptiles',
      'horses': 'Horses',
      'other': 'Other',
      'popular': 'Popular',
      'new_ads': 'New Listings',
      'see_all': 'All',
      'price': 'Price',
      'contact_seller': 'Contact',
      'call': 'Call',
      'telegram': 'Telegram',
      'add_to_favorites': 'Add to favorites',
      'remove_from_favorites': 'Remove from favorites',
      'login': 'Login',
      'register': 'Register',
      'phone': 'Phone',
      'password': 'Password',
      'name': 'Name',
      'my_ads': 'My Ads',
      'settings': 'Settings',
      'logout': 'Logout',
      'add_ad': 'Add Listing',
      'title': 'Title',
      'description': 'Description',
      'category': 'Category',
      'city': 'City',
      'publish': 'Publish',
      'no_favorites': 'No favorites',
      'no_ads': 'No listings',
      'select_language': 'Select language',
      'language': 'Language',
      'edit': 'Edit',
      'edit_profile': 'Edit Profile',
      'save': 'Save',
      'cancel': 'Cancel',
      'logout_confirm': 'Are you sure you want to logout?',
      'login_prompt': 'Login to post ads',
      'login_telegram': 'Login with Telegram',
      'notifications': 'Notifications',
      'messages': 'Messages',
      'messages_desc': 'New message notifications',
      'ads_notifications': 'Ads',
      'ads_notifications_desc': 'New ads in favorite categories',
      'news': 'News',
      'news_desc': 'Promotions and special offers',
      'about': 'About',
      'help': 'Help',
      'version': 'Version',
      'about_text': 'PetPet - convenient marketplace for buying and selling pets in Uzbekistan.',
      'contacts': 'Contacts',
      'close': 'Close',
      'breed': 'Breed',
      'age': 'Age',
      'vaccinated': 'Vaccinated',
      'negotiable': 'Negotiable',
      'popular_queries': 'Popular queries',
      'nothing_found': 'Nothing found',
      'try_different': 'Try a different query',
      'found': 'Found',
      'select_category': 'Select category',
      'select_photo': 'Select photo',
      'ad_created': 'Ad created',
      'fill_required': 'Fill required fields',
      'all_products': 'All Products',
      'search_products': 'Search products...',
      'animals': 'Animals',
      'choose_pet': 'Choose a pet',
      'products': 'Products',
      'for_pets': 'For your pets',
      'more': 'More',
      'food': 'Food',
      'toys': 'Toys',
      'cages': 'Cages',
      'empty_yet': 'Empty yet',
      'add_favorites_hint': 'Add ads you like\nto favorites',
      'go_to_search': 'Go to search',
      'clear': 'Clear',
      'clear_favorites': 'Clear favorites?',
      'clear_favorites_hint': 'All ads will be removed from favorites',
      'items_one': 'item',
      'items_few': 'items',
      'items_many': 'items',
      'new_ad': 'New Ad',
      'photos': 'Photos',
      'photos_hint': 'Add up to 8 photos. First photo will be main',
      'add_photo': 'Add photo',
      'main_photo': 'Main',
      'choose_from_gallery': 'Choose from gallery',
      'can_select_multiple': 'Can select multiple',
      'take_photo': 'Take photo',
      'open_camera': 'Open camera',
      'category_and_city': 'Category and city',
      'main_info': 'Main information',
      'ad_title': 'Ad title',
      'ad_title_hint': 'Example: British kitten, boy',
      'enter_title': 'Enter title',
      'enter_price': 'Enter price',
      'price_negotiable': 'Price negotiable',
      'price_negotiable_hint': 'Price is discussed with buyer',
      'pet_characteristics': 'Pet characteristics',
      'color': 'Color',
      'gender': 'Gender',
      'male': 'Male',
      'female': 'Female',
      'vaccinated_hint': 'Pet has all necessary vaccinations',
      'ad_description': 'Ad description',
      'ad_description_hint': 'Describe pet in detail: character, features...',
      'enter_description': 'Enter description',
      'contact_info': 'Contact information',
      'phone_number': 'Phone number',
      'enter_phone': 'Enter phone',
      'telegram_optional': 'Telegram (optional)',
      'free_posting': 'FREE posting',
      'ad_active_30_days': 'Ad will be active for 30 days',
      'promotion': 'Promotion',
      'your_ad_in_top': 'Your ad will be in top',
      'days': 'days',
      'publish_free': 'Publish for free',
      'ad_published': 'Ad published!',
      'ad_published_hint': 'Your ad has been successfully added and is now available',
      'top_activated': 'TOP activated!',
      'great': 'Great!',
      'max_8_photos': 'Maximum 8 photos',
      'add_at_least_one_photo': 'Add at least one photo',
      'dark_theme': 'Dark theme',
      'light_theme': 'Light theme',
      'theme': 'Theme',
      'filter': 'Filter',
      'sort_by': 'Sort by',
      'price_low_high': 'Price: low to high',
      'price_high_low': 'Price: high to low',
      'newest': 'Newest first',
      'apply': 'Apply',
      'reset': 'Reset',
      'view_grid': 'Grid',
      'view_list': 'List',
    },
    'uz': {
      'app_name': 'PetPet',
      'home': 'Bosh sahifa',
      'catalog': 'Katalog',
      'favorites': 'Sevimlilar',
      'profile': 'Profil',
      'search': 'Qidirish',
      'search_hint': 'Hayvonlarni qidirish...',
      'categories': 'Kategoriyalar',
      'all': 'Hammasi',
      'dogs': 'Itlar',
      'cats': 'Mushuklar',
      'birds': 'Qushlar',
      'fish': 'Baliqlar',
      'rodents': 'Kemiruvchilar',
      'reptiles': 'Sudralib yuruvchilar',
      'horses': 'Otlar',
      'other': 'Boshqalar',
      'popular': 'Mashhur',
      'new_ads': 'Yangi e\'lonlar',
      'see_all': 'Hammasi',
      'price': 'Narxi',
      'contact_seller': 'Bog\'lanish',
      'call': 'Qo\'ng\'iroq',
      'telegram': 'Telegram',
      'add_to_favorites': 'Sevimlilarga',
      'remove_from_favorites': 'Sevimlilardan olib tashlash',
      'login': 'Kirish',
      'register': 'Ro\'yxatdan o\'tish',
      'phone': 'Telefon',
      'password': 'Parol',
      'name': 'Ism',
      'my_ads': 'Mening e\'lonlarim',
      'settings': 'Sozlamalar',
      'logout': 'Chiqish',
      'add_ad': 'E\'lon qo\'shish',
      'title': 'Sarlavha',
      'description': 'Tavsif',
      'category': 'Kategoriya',
      'city': 'Shahar',
      'publish': 'E\'lon qilish',
      'no_favorites': 'Sevimlilar yo\'q',
      'no_ads': 'E\'lonlar yo\'q',
      'select_language': 'Tilni tanlang',
      'language': 'Til',
      'edit': 'Tahrirlash',
      'edit_profile': 'Profilni tahrirlash',
      'save': 'Saqlash',
      'cancel': 'Bekor qilish',
      'logout_confirm': 'Chiqishni xohlaysizmi?',
      'login_prompt': 'E\'lon qo\'shish uchun kiring',
      'login_telegram': 'Telegram orqali kirish',
      'notifications': 'Bildirishnomalar',
      'messages': 'Xabarlar',
      'messages_desc': 'Yangi xabarlar haqida bildirishnomalar',
      'ads_notifications': 'E\'lonlar',
      'ads_notifications_desc': 'Sevimli kategoriyalardagi yangi e\'lonlar',
      'news': 'Yangiliklar',
      'news_desc': 'Aksiyalar va maxsus takliflar',
      'about': 'Ilova haqida',
      'help': 'Yordam',
      'version': 'Versiya',
      'about_text': 'PetPet - O\'zbekistonda hayvonlarni sotib olish va sotish uchun qulay maydon.',
      'contacts': 'Kontaktlar',
      'close': 'Yopish',
      'breed': 'Zot',
      'age': 'Yoshi',
      'vaccinated': 'Emlangan',
      'negotiable': 'Kelishiladi',
      'popular_queries': 'Mashhur so\'rovlar',
      'nothing_found': 'Hech narsa topilmadi',
      'try_different': 'Boshqa so\'rov bilan urinib ko\'ring',
      'found': 'Topildi',
      'select_category': 'Kategoriyani tanlang',
      'select_photo': 'Rasmni tanlang',
      'ad_created': 'E\'lon yaratildi',
      'fill_required': 'Majburiy maydonlarni to\'ldiring',
      'all_products': 'Barcha mahsulotlar',
      'search_products': 'Mahsulotlarni qidirish...',
      'animals': 'Hayvonlar',
      'choose_pet': 'Hayvonni tanlang',
      'products': 'Mahsulotlar',
      'for_pets': 'Hayvonlaringiz uchun',
      'more': 'Ko\'proq',
      'food': 'Ozuqa',
      'toys': 'O\'yinchoqlar',
      'cages': 'Qafaslar',
      'empty_yet': 'Hali bo\'sh',
      'add_favorites_hint': 'Yoqtirgan e\'lonlarni\nsevimlilarga qo\'shing',
      'go_to_search': 'Qidiruvga o\'tish',
      'clear': 'Tozalash',
      'clear_favorites': 'Sevimlilarni tozalash?',
      'clear_favorites_hint': 'Barcha e\'lonlar sevimlilardan o\'chiriladi',
      'items_one': 'e\'lon',
      'items_few': 'e\'lon',
      'items_many': 'e\'lon',
      'new_ad': 'Yangi e\'lon',
      'photos': 'Rasmlar',
      'photos_hint': '8 tagacha rasm qo\'shing. Birinchi rasm asosiy bo\'ladi',
      'add_photo': 'Rasm qo\'shish',
      'main_photo': 'Asosiy',
      'choose_from_gallery': 'Galereyadan tanlash',
      'can_select_multiple': 'Bir nechtasini tanlash mumkin',
      'take_photo': 'Rasm olish',
      'open_camera': 'Kamerani ochish',
      'category_and_city': 'Kategoriya va shahar',
      'main_info': 'Asosiy ma\'lumot',
      'ad_title': 'E\'lon sarlavhasi',
      'ad_title_hint': 'Masalan: Britaniya mushukchasi, erkak',
      'enter_title': 'Sarlavha kiriting',
      'enter_price': 'Narx kiriting',
      'price_negotiable': 'Narxi kelishiladi',
      'price_negotiable_hint': 'Narx xaridor bilan muhokama qilinadi',
      'pet_characteristics': 'Hayvon xususiyatlari',
      'color': 'Rang',
      'gender': 'Jinsi',
      'male': 'Erkak',
      'female': 'Urg\'ochi',
      'vaccinated_hint': 'Hayvon barcha kerakli emlarga ega',
      'ad_description': 'E\'lon tavsifi',
      'ad_description_hint': 'Hayvonni batafsil tasvirlab bering...',
      'enter_description': 'Tavsif kiriting',
      'contact_info': 'Aloqa ma\'lumotlari',
      'phone_number': 'Telefon raqami',
      'enter_phone': 'Telefon kiriting',
      'telegram_optional': 'Telegram (ixtiyoriy)',
      'free_posting': 'BEPUL joylashtirish',
      'ad_active_30_days': 'E\'lon 30 kun faol bo\'ladi',
      'promotion': 'Reklama',
      'your_ad_in_top': 'E\'loningiz tepada bo\'ladi',
      'days': 'kun',
      'publish_free': 'Bepul e\'lon qilish',
      'ad_published': 'E\'lon e\'lon qilindi!',
      'ad_published_hint': 'E\'loningiz muvaffaqiyatli qo\'shildi va allaqachon mavjud',
      'top_activated': 'TOP faollashtirildi!',
      'great': 'Ajoyib!',
      'max_8_photos': 'Maksimum 8 ta rasm',
      'add_at_least_one_photo': 'Kamida bitta rasm qo\'shing',
      'dark_theme': 'Qorong\'i mavzu',
      'light_theme': 'Yorug\' mavzu',
      'theme': 'Mavzu',
      'filter': 'Filtr',
      'sort_by': 'Saralash',
      'price_low_high': 'Narx: pastdan yuqoriga',
      'price_high_low': 'Narx: yuqoridan pastga',
      'newest': 'Avval yangilari',
      'apply': 'Qo\'llash',
      'reset': 'Tiklash',
      'view_grid': 'Panjara',
      'view_list': 'Ro\'yxat',
    },
  };

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLanguage = prefs.getString('language') ?? 'ru';
    _isInitialized = true;
    notifyListeners();
  }

  Future<void> setLanguage(String langCode) async {
    _currentLanguage = langCode;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString('language', langCode);
    notifyListeners();
  }

  String tr(String key) {
    return _translations[_currentLanguage]?[key] ??
           _translations['ru']?[key] ??
           key;
  }

  String get flagEmoji {
    switch (_currentLanguage) {
      case 'ru':
        return '🇷🇺';
      case 'en':
        return '🇬🇧';
      case 'uz':
        return '🇺🇿';
      default:
        return '🌐';
    }
  }

  String get languageName {
    switch (_currentLanguage) {
      case 'ru':
        return 'Русский';
      case 'en':
        return 'English';
      case 'uz':
        return 'O\'zbek';
      default:
        return 'Русский';
    }
  }

  static List<Map<String, String>> get availableLanguages => [
    {'code': 'ru', 'name': 'Русский', 'flag': '🇷🇺'},
    {'code': 'en', 'name': 'English', 'flag': '🇬🇧'},
    {'code': 'uz', 'name': 'O\'zbek', 'flag': '🇺🇿'},
  ];
}
